### ISSUE TITLE
advanced-ssh-config

### ISSUE THREAD

**Issue by ivomarino** [ttssdev/appflow#11]
Support https://github.com/moul/advanced-ssh-config/blob/master/README.md.

**Comment by derpaschi** [comment]
To set the default `User` for all assh connections you can add a `defaults` section to your `~/.ssh/assh_personal.yml`

example:

```
hosts:
  # your personal hosts

defaults:
  User: paschi
```

**Comment by ivomarino** [comment]
Great, thanks. All other personal things or personal nodes should go there too.

**Comment by ivomarino** [comment]
Be sure that empty `hosts` yaml declaration does not overwrite settings, check with `make ssh` after changes in the file, `assh config list` shows settings then.
