### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by ivomarino** [ttssdev/appflow#112]
Would be nice to introduce `appflow -v` or `appflow --version` in order to see which version is running. 
We should also provide a verbose version of the provision process

**Comment by 89luca89** [comment]
Still we want to add the verbose provision process.

**Comment by ivomarino** [comment]
has been implemented with https://github.com/ttssdev/appflow/commit/ef730e5a1fc6905bf1fdee0cbfb514d24daf8a46.
