### ISSUE TITLE
`appflow vhosts` adds too many newlines 

### ISSUE THREAD

**Issue by ocean90** [ttssdev/appflow#115]
Tested on macOS with latest version.

**Before:**
```
127.0.0.1		localhost
```

**First run:**

```
127.0.0.1		localhost


192.168.80.2 atlantis

```
(Two before, one after)

**Second run:**
```
127.0.0.1		localhost


192.168.80.2 atlantis



```
(Two before, three after)

**Third run:**
```
127.0.0.1		localhost


192.168.80.2 atlantis





```
(Two before, five after)

**Comment by ivomarino** [comment]
hi @ocean90, thanks for reporting this, the issue probably is here: https://github.com/ttssdev/appflow/blob/master/lib/appflow_tools.py#L136-L137 -- we take a look for fixing this asap.

**Comment by 89luca89** [comment]
Eventually we can switch to this library https://github.com/jonhadfield/python-hosts
this will ease the management of the hosts

**Comment by 89luca89** [comment]
Should be fixed now.
