### ISSUE TITLE
Preventing encrypted data being overwritten by different user

### ISSUE THREAD

**Issue by watzak** [ttssdev/appflow#116]
Hello @ivomarino , hello @89luca89 

Did u already thought on implementing a way to prevent that encrypted data can be overwritten by users?

If not, have a look at https://www.vaultproject.io/

Cheers watzak ;)

**Comment by ivomarino** [comment]
@watzak `appflow checkin` actually should prevent exactly this, it ensures that sensitive data is encrypted and pushes this to the repo. Obviously you could "override" this manually and push unencrypted stuff to the repo. Supporting the vaultproject.io as backend for keeping sensitive data could be a good improvement anyway, thanks for the hint. Can we consider this issue more an "enhancement" for future nice-to-have?

**Comment by watzak** [comment]
Sure, it's more considered as a nice to have feature in the future ;)

**Comment by ivomarino** [comment]
@watzak ok, I'll close this then as far it's not considered a real bug or blocker, we can reopen it again asap we come along this topic or similar. Thanks for the suggestion in the meantime.
