### ISSUE TITLE
appflow - woodwing - add module contentstation

### ISSUE THREAD

**Issue by stefan-kalb** [ttssdev/appflow#119]
Enhance appflow for deployment of woodwing contentstation web and plugin.

**Comment by ivomarino** [comment]
hi @stefan-kalb, are you going to open a pull request for this?

**Comment by stefan-kalb** [comment]
Yes, I will as soon as everything is tested.

**Comment by ivomarino** [comment]
ok, thanks.

**Comment by ivomarino** [comment]
@gerritdamenmms, @stefan-kalb has this been merged by https://github.com/ttssdev/appflow-playbooks/pull/9? Thanks
