### ISSUE TITLE
Security: Disable Directory Listing

### ISSUE THREAD

**Issue by swissspidy** [ttssdev/appflow#16]
- [x] Disable Directory Listing everyhwere.
- [ ] Disallow executing PHP directly in `wp-includes` and `web/app`.

**Comment by ivomarino** [comment]
`Disable Directory Listing everyhwere` has been implemented with https://github.com/ttssdev/appflow/commit/68b9e2ff1041bd9d391cb15d97d3e4ef08ae41b0, verified by @swissspidy.

**Comment by ivomarino** [comment]
@swissspidy any code for `Disallow executing PHP directly in wp-includes and web/app`?

**Comment by swissspidy** [comment]
Usually we'd do something like this:

```apache
<Directory "/app/uploads/">
<Files "*.php">
Order Deny,Allow
Deny from All
</Files>
</Directory>
```

But apparently, we can easily set this via iThemes Security. As long as the current `.htaccess` from that plugin is correct, it should work. It does this by adding new rewrite rules:

```apache
<IfModule mod_rewrite.c>
	RewriteEngine On

	# Protect System Files - Security > Settings > System Tweaks > System Files
	RewriteRule ^wp-admin/install\.php$ - [F]
	RewriteRule ^wp-admin/includes/ - [F]
	RewriteRule !^wp-includes/ - [S=3]
	RewriteRule ^wp-includes/[^/]+\.php$ - [F]
	RewriteRule ^wp-includes/js/tinymce/langs/.+\.php - [F]
	RewriteRule ^wp-includes/theme-compat/ - [F]

	# Disable PHP in Uploads - Security > Settings > System Tweaks > PHP in Uploads
	RewriteRule ^app/uploads/.*\.(?:php[1-7]?|pht|phtml?|phps)$ - [NC,F]

	# …
</IfModule>
```

How can I update the `.htaccess` with the latest updates from iThemes security to test this?

**Comment by ivomarino** [comment]
Implemented first part with https://github.com/ttssdev/appflow/commit/68b9e2ff1041bd9d391cb15d97d3e4ef08ae41b0.

**Comment by ivomarino** [comment]
@swissspidy take a look at https://github.com/ttssdev/appflow/blob/master/playbooks/roles/web/templates/wp_bedrock/htaccess.j2 -- we provision this as default `.htaccess`. When we set `htaccess_ithemes_security_enable: true` for a `vhost` in `conf_vhosts_common` we also enable all the  iThemes Security Config Details which should include what you need, take a look at the file.
