### ISSUE TITLE
Performance: Enable HTTP/2

### ISSUE THREAD

**Issue by swissspidy** [ttssdev/appflow#17]
See also https://info.varnish-software.com/blog/now-available-varnish-cache-5-http2-support

**Comment by ocean90** [comment]
Not 100% sure if HAProxy supports HTTP/2 or not. I think 1.7 does but AppFlow has 1.6.11 installed.

A few posts with configs which may be useful for us:
* http://discourse.haproxy.org/t/what-are-the-plans-for-http-2/38/3
* https://gist.github.com/matthiasg/ccd8ffd41f98ed70eaf91a81fd1c24dc
* http://undying.github.io/2016/01/12/haproxy-elb-nginx-http2.html
* https://webtide.com/http2-with-haproxy-and-jetty/
* http://www.eclipse.org/jetty/documentation/current/http2-configuring-haproxy.html
* https://ispire.me/http2-ssl-offloading-with-haproxy-and-nginx/

**Comment by ivomarino** [comment]
Has been introduced with https://github.com/ttssdev/appflow-playbooks/commit/5aaa67302e5e8d5e8c5cb6862352268e14bc87e3 which closes this issue also.
