### ISSUE TITLE
Upgrade to PHP 7

### ISSUE THREAD

**Issue by swissspidy** [ttssdev/appflow#18]

**Comment by swissspidy** [comment]
Note that PHP 7.1 is now available and should be considered.

**Comment by ivomarino** [comment]
This has to be extensively tested, we check this anyway asap.

**Comment by ivomarino** [comment]
will be implemented in branch [18-php7-support](https://github.com/ttssdev/appflow/tree/18-php7-support).
The basic idea is to variabilize [php.yml](https://github.com/ttssdev/appflow/blob/18-php7-support/playbooks/roles/web/tasks/php.yml#L30-L50) with something like this:

```
    ...
    - libapache2-mod-php{{ conf_php_version_debian_family }}
    - libapache2-mod-rpaf
    - apachetop
    - php{{ conf_php_version_debian_family }}
    - php{{ conf_php_version_debian_family }}-cli
    - php{{ conf_php_version_debian_family }}-gd
    - php{{ conf_php_version_debian_family }}-json
    - php{{ conf_php_version_debian_family }}-mysql
    - php{{ conf_php_version_debian_family }}-tidy
    - php{{ conf_php_version_debian_family }}-curl
    - php{{ conf_php_version_debian_family }}-gd
    - php{{ conf_php_version_debian_family }}-imagick
    - php{{ conf_php_version_debian_family }}-imap
    - php{{ conf_php_version_debian_family }}-intl
    - php{{ conf_php_version_debian_family }}-ldap
    - php{{ conf_php_version_debian_family }}-mcrypt
    - php{{ conf_php_version_debian_family }}-gettext
    - php{{ conf_php_version_debian_family }}-xml
    - php{{ conf_php_version_debian_family }}-mbstring
    - php{{ conf_php_version_debian_family }}-soap
    - php{{ conf_php_version_debian_family }}-zip
    ...
```

then we can set something like this in the tenant's `group_vars/webservers` [PHP section](https://github.com/ttssdev/appflow/blob/master/examples/appflow-mrrobot/development/group_vars/webservers#L48):

```
...
# conf_php_version_debian_family: 5.6
conf_php_version_debian_family: 7.1
...
```

for CentOS it would be `conf_php_version_redhat_family` and so on.
This has been tested on Ubuntu 14.04 and seems to work fine:

![screen shot 2017-02-24 at 13 54 11](https://cloud.githubusercontent.com/assets/4869961/23304220/e29edbfe-fa98-11e6-8ed5-4efb4ccf28e2.png)

for the `PHP 5.6 -> 7.1` transition we probably need something like:
`appflow provision limit=atlantis tags=php,apache2`.

**Comment by ivomarino** [comment]
@ocean90 can be closed?

**Comment by ocean90** [comment]
Yep.
