### ISSUE TITLE
create one-liner installation

### ISSUE THREAD

**Issue by ivomarino** [ttssdev/appflow#22]
would ne nice to have a one-liner installation of AppFlow like `brew`: `/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`. We can then reference this in https://github.com/ttssdev/appflow/wiki/Walkthrough.

**Comment by 89luca89** [comment]
We don't use ruby, we use bash, for example:

`bash -c 'su -c "curl http://folkswithhats.org/fedy-installer -o fedy-installer && chmod +x fedy-installer && ./fedy-installer"'`

**Comment by 89luca89** [comment]
Closed by:
[This](https://github.com/ttssdev/appflow/blob/master/utils/install_appflow)

**Comment by ivomarino** [comment]
@89luca89 during install we execute `vagrant plugin install vagrant-cachier` which requires `sudo apt install zlib1g-dev` on `Debian Family`. We also need to install `ansible` on `Debian Family`: http://docs.ansible.com/ansible/intro_installation.html#latest-releases-via-apt-debian
