### ISSUE TITLE
tmate daemon for easy access on atlantis

### ISSUE THREAD

**Issue by 89luca89** [ttssdev/appflow#23]
We need a small tmate daemon on atlantis to be easly accessible for remote assistance

**Comment by ivomarino** [comment]
we need to be sure that the service then starts on boot.

**Comment by ivomarino** [comment]
interesting approach could be https://github.com/gravitational/teleport/blob/master/docs/quickstart.md.

**Comment by ivomarino** [comment]
as key/value store we should use http://www.kvstore.io.

**Comment by ivomarino** [comment]
@89luca89 when `appflow support` has been launched and the session has expired a new launch will send a mail regarding the old session, we should pre-execute a `killall -9 tmate`.

**Comment by ivomarino** [comment]
will be closed for now, `tmate` session are opened by users on request.
