### ISSUE TITLE
appflow bin

### ISSUE THREAD

**Issue by ivomarino** [ttssdev/appflow#25]
We want `% appflow provision=<tenant> ...`.
Should be a `wrapper` around `Makefile` to start.

`appflow -> /usr/local/bin/appflow`
`library -> /usr/local/share/appflow`

this will lead to introduction of `development` and `stable` releases.

**Comment by 89luca89** [comment]
This feature is now implemented as of [this](https://github.com/ttssdev/appflow/commit/11922dca47882166df76a7ea01f1a5f82eb0dda7)
