### ISSUE TITLE
Support for managing root certificates

### ISSUE THREAD

**Issue by stefan-kalb** [ttssdev/appflow#26]
As an administrator I want to be able to manage the available root certificates on my servers.
E.g. I want to add self signed root certificates.
To do this I want to be able to do the following manual steps with appflow:

- mkdir /usr/share/ca-certificates/extra
- cp AnyRootCert.crt /usr/share/ca-certificates/extra/
- add the new certificate to /etc/ca-certificates.conf
- make the certificates available system wide: dpkg-reconfigure ca-certificates

**Comment by ivomarino** [comment]
AppFlow actually manages virtualhost certs in `/etc/certs/`, what kind of certs are this in your example?

**Comment by stefan-kalb** [comment]
just self issued certificates. I think the certificates can also be stored in /etc/cert if the certs are known systemwide, for example for access sites with curl

**Comment by ivomarino** [comment]
so those certs are required for executing .e.g `curl http://myservice.inernal` on the node?
`myservice.inernal` would be something like your `AD` or similar?

**Comment by stefan-kalb** [comment]
That's it, but its curl `https://mysqervice.internal` of course :-)

**Comment by ivomarino** [comment]
can be closed for now according to @stefan-kalb.
