### ISSUE TITLE
Turn off PHP sessions

### ISSUE THREAD

**Issue by swissspidy** [ttssdev/appflow#30]
In the global `php.ini` file, PHP sessions are currently turned on automatically. That means a `PHPSESSID` cookie is set even though it's not being used or enforced by a project.

**Comment by ivomarino** [comment]
@swissspidy has this been fixed?

**Comment by swissspidy** [comment]
@ivomarino After a second glance it turned out appflow wasn't the culprit 🙈

**Comment by ivomarino** [comment]
Ok, good to know, thanks.
