### ISSUE TITLE
Raise default Vagrant memory value to 4GB

### ISSUE THREAD

**Issue by ivomarino** [ttssdev/appflow#31]
Considering the today most devs have machines with at least 8 or 16GB of physical RAM we could start considering to increase the default Vagrant memory value to 4GB, actually it's set to 2GB as defined in https://github.com/ttssdev/appflow/blob/master/Vagrantfile#L44. 

Especially MySQL intensive tasks and queries could take advantage of more memory, actually some `atlantis` nodes crash during while executing some heavy queries, like reported by @hubeRsen and @grappler.

**Comment by ocean90** [comment]
> machines with at least 8 or 16GB of physical RAM we could start considering to increase the default Vagrant memory value to 4GB,

That might be true, but this VM isn't the only process which is running on our machines. Think about IDEs, Chrome, Slack, and maybe other VMs which are running parallel to the `atlantis` VM.
IMO the memory value should only be increased if we know for sure that low memory is the real cause for this or if it's just a faulty setting somewhere.

**Comment by ivomarino** [comment]
makes sense to me, thanks @ocean90, so let's investigate what pushes the memory usage high.

**Comment by ivomarino** [comment]
We should run some benchmarks e.g. with https://github.com/wg/wrk for http and some MySQL bench/stress test tool.

**Comment by ivomarino** [comment]
For MySQL something like this could do https://www.howtoforge.com/how-to-benchmark-your-system-cpu-file-io-mysql-with-sysbench#-mysql-benchmark-

**Comment by grappler** [comment]
@ivomarino What is the progress on this as I need to restart atlantis at least twice a day and it takes time to get back as I get "503 Service Unavailable" in the first couple of minutes after reloading it.

**Comment by ivomarino** [comment]
@grappler so the main issue where missing images? is CPU load OK now?

**Comment by grappler** [comment]
The stability has improved a bit. I don't think the issue is the missing images. Here are log files from monit. This was from Jan 16th.
https://required.slack.com/files/grapplerulrich/F3S11LUCD/pasted_image_at_2017_01_16_09_54_am.png
https://required.slack.com/files/grapplerulrich/F3SJFH8NA/monit_logfile.txt

I can't increase the memory to 4GB as I have troubles now when Appflow takes a full 2GB.

I have implemented Dominik's htaccess fix for the images. Let see if that makes any difference.

**Comment by ivomarino** [comment]
@grappler allright, let's see, thanks for update;)

**Comment by grappler** [comment]
I am getting now 503 Service Unavailable.

![image](https://cloud.githubusercontent.com/assets/1785641/22465610/dc7a83ac-e7bc-11e6-91c6-bde209f11ea9.png)

**Comment by ivomarino** [comment]
@grappler `uptime` of the VM? `ssh atlantis "uptime"`

**Comment by grappler** [comment]
@ivomarino uptime, 3h 8m

**Comment by ivomarino** [comment]
let's check which service is not running:

```
ssh atlantis
sudo service apache2 status ; sudo service haproxy status ; ps aux | grep varnish
```

paste output, thanks.

**Comment by grappler** [comment]
Atlantis was unresponsive again today morning.

**Comment by grappler** [comment]
Atlantis was unresponsive again after 36 mins

The result from `sudo service apache2 status ; sudo service haproxy status ; ps aux | grep varnish`
```
 * apache2 is running
debug1: multiplexing control connection
debug1: channel 3: new [mux-control]
debug1: channel 4: new [client-session]
debug1: multiplexing control connection
debug1: channel 5: new [mux-control]
debug1: channel 6: new [client-session]
debug1: multiplexing control connection
debug1: channel 7: new [mux-control]
debug1: channel 8: new [client-session]
debug1: channel 5: free: mux-control, nchannels 9
debug1: client_input_channel_req: channel 6 rtype exit-status reply 0
debug1: client_input_channel_req: no sink for exit-status on channel 6
debug1: channel 6: free: client-session, nchannels 8
debug1: channel 3: free: mux-control, nchannels 7
debug1: client_input_channel_req: channel 4 rtype exit-status reply 0
debug1: client_input_channel_req: no sink for exit-status on channel 4
debug1: channel 4: free: client-session, nchannels 6
debug1: multiplexing control connection
debug1: channel 3: new [mux-control]
debug1: channel 4: new [client-session]
debug1: channel 3: free: mux-control, nchannels 7
debug1: client_input_channel_req: channel 4 rtype exit-status reply 0
debug1: client_input_channel_req: no sink for exit-status on channel 4
debug1: channel 4: free: client-session, nchannels 6
```

**Comment by ivomarino** [comment]
for now we remain on 2G which allows to run multiple VMs also on Macs with e.g. 8G RAM.
