### ISSUE TITLE
appflow vagrant

### ISSUE THREAD

**Issue by ivomarino** [ttssdev/appflow#35]
actually when running `appflow vagrant reload atlantis` instead of `appflow vm reload atlantis` we get this:

```
mkdir -p ~/Downloads/Software
mkdir -p ~/Downloads/Software/Vagrant-Boxes
cd ~/Downloads/Software/Vagrant-Boxes &&  wget -c http://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box  && mv trusty-server-cloudimg-amd64-vagrant-disk1.box trusty64.box && cd ~/Documents/webdev/appflow
--2017-01-11 11:13:54--  http://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box
Resolving cloud-images.ubuntu.com...
```

we should avoid this in order to break things, so maybe `appflow vagrant` should be an alias for `appflow vm`.

**Comment by 89luca89** [comment]
As suggested, now you control the VMs with
`appflow vagrant <command>`

To initialize a VM
`appflow init-vm`
A small tool will ask the distro you want
