### ISSUE TITLE
atlantis monitoring

### ISSUE THREAD

**Issue by ivomarino** [ttssdev/appflow#37]
as suggested by @grappler we should provide `atlantis` with adequate monitoring, options are:
- `monit` ([bottom-up](https://mmonit.com/monit/documentation/monit.html#MANAGE-YOUR-MONIT-INSTANCES))
- https://github.com/prometheus/node_exporter
- `icinga2` (top-down)
- `munin` (top-down)
- https://nicolargo.github.io/glances/

**Comment by ivomarino** [comment]
munin has been implemented with https://github.com/ttssdev/appflow/commit/07afbc56470cdfc5bde26826fea4bf0696c7e948.

**Comment by ocean90** [comment]
Plugins which I think are also interesting for us:

* [mysql_bytes](https://github.com/munin-monitoring/munin/blob/203a4210fddcc393aee4ed0b8480b9c9f02955b7/plugins/node.d/mysql_bytes)
* [mysql_queries](https://github.com/munin-monitoring/munin/blob/203a4210fddcc393aee4ed0b8480b9c9f02955b7/plugins/node.d/mysql_queries)
* [mysql_threads](https://github.com/munin-monitoring/munin/blob/203a4210fddcc393aee4ed0b8480b9c9f02955b7/plugins/node.d/mysql_threads)
* [mysql_slowqueries](https://github.com/munin-monitoring/munin/blob/203a4210fddcc393aee4ed0b8480b9c9f02955b7/plugins/node.d/mysql_slowqueries)
* [varnish_](https://github.com/munin-monitoring/munin/blob/203a4210fddcc393aee4ed0b8480b9c9f02955b7/plugins/node.d/varnish_)
   * Plugin requires the XML::Parser module
      ```
      Can't locate XML/Parser.pm in @INC (you may need to install the XML::Parser module) (@INC contains: /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at /usr/share/munin/plugins/varnish_ line 94.
      BEGIN failed--compilation aborted at /usr/share/munin/plugins/varnish_ line 94.
      ```

To install the plugins on atlantis I did the following steps:

```
# Install perl module (My answers were: yes, sudo)
cpan XML::Parser

# Create symlinks
sudo ln -s /usr/share/munin/plugins/varnish_ /etc/munin/plugins/varnish_memory_usage;
sudo ln -s /usr/share/munin/plugins/varnish_ /etc/munin/plugins/varnish_expunge;
sudo ln -s /usr/share/munin/plugins/varnish_ /etc/munin/plugins/varnish_hit_rate;
sudo ln -s /usr/share/munin/plugins/varnish_ /etc/munin/plugins/varnish_objects;
sudo ln -s /usr/share/munin/plugins/varnish_ /etc/munin/plugins/varnish_bad;
sudo ln -s /usr/share/munin/plugins/varnish_ /etc/munin/plugins/varnish_backend_traffic;
sudo ln -s /usr/share/munin/plugins/varnish_ /etc/munin/plugins/varnish_transfer_rates;
sudo ln -s /usr/share/munin/plugins/varnish_ /etc/munin/plugins/varnish_request_rate;
sudo ln -s /usr/share/munin/plugins/varnish_ /etc/munin/plugins/varnish_threads;
sudo ln -s /usr/share/munin/plugins/varnish_ /etc/munin/plugins/varnish_uptime;

sudo ln -s /usr/share/munin/plugins/mysql_bytes /etc/munin/plugins/;
sudo ln -s /usr/share/munin/plugins/mysql_queries /etc/munin/plugins/;
sudo ln -s /usr/share/munin/plugins/mysql_threads /etc/munin/plugins/;
sudo ln -s /usr/share/munin/plugins/mysql_slowqueries /etc/munin/plugins/;

# Restart munin node
sudo service munin-node restart
```

Varnish graphs:
![screenshot-atlantis-8080 2017-02-26 13-31-41](https://cloud.githubusercontent.com/assets/617637/23339697/f25f6938-fc27-11e6-80fd-4fcf040edeec.png)

MySQL graphs:
![screenshot-atlantis-8080 2017-02-26 13-30-22](https://cloud.githubusercontent.com/assets/617637/23339675/cc85bee2-fc27-11e6-811a-4e1783c4f4b0.png)

**Comment by ivomarino** [comment]
@ocean90 maybe a plugin for HAProxy could also be relevant.

**Comment by ivomarino** [comment]
Implemented.
