### ISSUE TITLE
Include domain or IP in bash prompt

### ISSUE THREAD

**Issue by ocean90** [ttssdev/appflow#40]
<img width="531" alt="" src="https://cloud.githubusercontent.com/assets/617637/22110571/78351bf0-de5c-11e6-84cf-c1825b6a989b.png">

**Comment by ocean90** [comment]
```
deploy@compute-01 ~ % cat .zshrc
# Set up the prompt

autoload -Uz promptinit
promptinit
prompt adam1
```

Checked some of the other themes, none of them are using `\H` for the host, which is the placeholder for the fully qualified domain name (or FQDN).

```
deploy@compute-01 ~ % hostname
compute-01
deploy@compute-01 ~ % hostname -f
compute-01.ch.example.ch
```

**Comment by ivomarino** [comment]
we should define a file in `etc` with some vars to source

**Comment by ivomarino** [comment]
code for this is here https://github.com/ttssdev/appflow/blob/master/playbooks/roles/common/tasks/main.yml#L87-L91, currently disabled.

**Comment by ocean90** [comment]
Quote from [GitLab.com Database Incident](https://docs.google.com/document/d/1GCK53YDcBWQveod9kfzW-VCxIABGiryG7_z_6jHdVik/pub):
> **TODO after data restored:**
> * Create issue to change terminal PS1 format/colours to make it clear whether you’re using production or staging (red production, yellow staging)
> * Show the full hostname in the bash prompt for all users by default (e.g., “db1.staging.gitlab.com” instead of just “db1”)

**Comment by ivomarino** [comment]
one idea is to leave hostname like it is:

`user@compute-01`

but change the color:

 - green: development
 - blue: testing
 - yellow: staging
 - red: production

@ocean90 what do you think?

**Comment by ocean90** [comment]
Would `user@compute-01 [staging]` (plus color) work too?

**Comment by ivomarino** [comment]
@ocean90 could be an option, basic idea is to keep the prompt as short as possible so maybe:

```
user@compute-01 [dev]
user@compute-01 [test]
user@compute-01 [stage]
user@compute-01 [prod]
```

I would suggest to start by grades, so first color, if we see it's not sufficient let's add also the suffix, ok?

**Comment by ocean90** [comment]
Isn't it possible to disable or change colors? That's what I see in iTerm:

<img width="167" alt="bildschirmfoto 2017-02-02 um 12 21 31" src="https://cloud.githubusercontent.com/assets/617637/22547709/34edca26-e943-11e6-9bd1-47f6b34626ee.png">

Colors are probably fine for the start but I always prefer text as it's more accessible. Don't forget that there are people with red–green color blindness. :)

**Comment by ivomarino** [comment]
True, also: http://serverfault.com/a/323155 ;)

**Comment by ivomarino** [comment]
For now I won't implement this, if someone would like to take it over feel free to open a pull request.
