### ISSUE TITLE
Add support for a memory object caching system

### ISSUE THREAD

**Issue by ocean90** [ttssdev/appflow#43]
... like [Memcached](https://memcached.org/).

The [memcache module for PHP](https://github.com/ttssdev/appflow/blob/b81a23a09dc51b16da8769baf1fd4f0b09642a74/playbooks/roles/web/tasks/php.yml#L51) is already available (maybe we should make Memcached (with d) available too), but no server.

Could https://github.com/geerlingguy/ansible-role-memcached be useful for this?

**Comment by ivomarino** [comment]
@ocean90 we just need to re-enable it here: https://github.com/ttssdev/appflow/blob/master/playbooks/roles/web/tasks/php.yml#L60

**Comment by ivomarino** [comment]
@ocean90 can you try to enable the package shown above, provision `ansible` and test? should work out-of-the-box.

**Comment by ocean90** [comment]
Sure, doing that now. Is https://github.com/ttssdev/appflow/blob/31c14c6caa327fc6cc0cf6ac5f9c87ba000e6c8c/playbooks/roles/web/tasks/main.yml#L43 related?

**Comment by ivomarino** [comment]
@ocean90 yep, may be useful, thanks for hint (didn't remember).

**Comment by ocean90** [comment]
So far enabling the `memcache` line is working for me. I haven't found the configs yet so I'm curious how it's set up, especially if you have more than one server.

**Comment by ocean90** [comment]
Fixed with #49.
