### ISSUE TITLE
Support an optional commit message for checkins

### ISSUE THREAD

**Issue by ocean90** [ttssdev/appflow#44]
The [current commit message](https://github.com/ttssdev/appflow/blob/fc468d1a9df33dbbe976b791764c2f2f8ca11d4a/utils/checkin.sh#L32) is "Auto commit".

I think it would be nice to be able to define a custom message. Example: `appflow checkin env=production -m "Added new host"`

**Comment by ivomarino** [comment]
jep, sounds good, @89luca89 what do you think? should be quite easy to implement, right?

**Comment by ocean90** [comment]
Untested:
```sh
for i in "$@"
do
case $i in
    -m=*|--message=*)
    COMMITMESSAGE="${i#*=}"
    shift # past argument=value
    ;;
    *)
            # unknown option
    ;;
esac

COMMITMESSAGE="${COMMITMESSAGE:-Auto commit}"

# …

git -C ~/.appflow/tenant/$tenant commit -m "$COMMITMESSAGE"
```

**Comment by ivomarino** [comment]
will be implement in the AppFlow Symfony CLI: https://github.com/ttssdev/appflow/issues/55.
