### ISSUE TITLE
Improve default Varnish config

### ISSUE THREAD

**Issue by ocean90** [ttssdev/appflow#47]
Current file: https://github.com/ttssdev/appflow/blob/3326173f651a4e6b5ace960f167d56659a2221ff/playbooks/roles/web/templates/etc/varnish/default.vcl.j2

I'd like to see a few things changed:

* [ ] The default cache time should be increased, it's currently 2 minutes (https://github.com/nicolargo/varnish-nginx-wordpress/blob/master/varnish/varnish4-wordpress#L203-L206)
* [x] Add cache hit/miss headers to make debugging easier (https://gist.github.com/ryan-frankel/10271802#file-varnishwithwordpress-vcl-L174-L187)
* [x] Ignore some WordPress cookies (https://github.com/nicolargo/varnish-nginx-wordpress/blob/master/varnish/varnish4-wordpress#L78-L99)
* [ ] What else? Put them in the comments.

Some resources:

* http://ryanfrankel.com/using-varnish-with-wordpress/
* https://konstantin.blog/2011/my-website-is-now-super-fast-with-varnish/
* https://konstantin.blog/2011/varnish-and-preview-posts-in-wordpress/
* http://pastebin.com/7KpZrAG0
* http://perrymitchell.net/article/a-load-balanced-website-using-php-fpm-nginx-mysql-and-varnish-part-3/

**Comment by ivomarino** [comment]
@ocean90 in order to do this we need to introduce some new `{{ conf_varnish_* }}` vars so first question is: what needs to be tuneable via vars and what features can directly be hardcoded into the configuration?

**Comment by ocean90** [comment]
Right, a few settings should be default and probably changeable via a config var.

Found another thing: Cookies are currently not removed from images. https://www.varnish-cache.org/lists/pipermail/varnish-misc/2011-February/019915.html should help for this.

**Comment by ocean90** [comment]
HAProxy has a balance option which is [`leastconn` by default ](https://github.com/ttssdev/appflow/blob/3e00d123b56776a347cc519f0e1c3a1ec16bd75e/examples/appflow-mrrobot/development/group_vars/all#L69). I guess this makes sense for Apache but I found several posts which suggest `uri` for Varnish, see http://stackoverflow.com/a/16901584/3507335 and http://blog.haproxy.com/2012/08/25/haproxy-varnish-and-the-single-hostname-website/ (scroll to the Configuration section).
Thoughts on that?

https://cbonte.github.io/haproxy-dconv/configuration-1.6.html#4.2-balance
