### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by ivomarino** [ttssdev/appflow#5]
We want to add `continuous integration` via Jenkins to the AppFlow development process.
This means when we push to `master` or some else `to-define` branch we automatically:
- Create `atlantis` or `atlantis.centos` from scratch each time.
- Start a clean `AppFlow` provisioning for that new node.
- Send results via mail or notify in Slack.
- Destroy the created Vagrant VM.
- Restart the process.

all this via Jenkins which can run remotely or locally.

**Comment by ivomarino** [comment]
We've started using a solution based on Docker and Jenkins.

**Comment by sneaker** [comment]
Hi Ivo

I recently implemented this using gitlab. Everything based on docker. Maybe you want to have a look at it https://about.gitlab.com/gitlab-ci/
Gitlab also provides a git repository and a new issue tracking system. It can be hosted by yourself or use a free (for closed source development) version on gitlab.com. You really can feel that it is from one hand. It works much better than all this plugins from various sources on jenkins.

Maybe worth a look
Best, Thomas

**Comment by ivomarino** [comment]
thanks @sneaker, sounds great I'll take a look. Since yesterday we're running Jenkins as a simple [docker-compose](https://github.com/ttssdev/appflow/blob/master/docker-compose.yml) process on OSX and Linux:

<img width="981" alt="atlantis_ci" src="https://cloud.githubusercontent.com/assets/4869961/19726330/b4f37510-9b8a-11e6-8a90-0c02f24e4539.png">

it's actually quite simple, Jenkins in Docker connects back to the `dockerhost` (bare metal notebook) via `ssh` destroys and recreates Vagrant boxes there in order to provision them from scratch each time, seems starting to work for now;)

**Comment by ivomarino** [comment]
we have a first complete AppFlow run via Jenkins on `testing`:

![atlantis_ci_success](https://cloud.githubusercontent.com/assets/4869961/19736872/77c4951c-9bb1-11e6-9980-f7491b9f59b5.png)

**Comment by ivomarino** [comment]
Introduced with https://github.com/ttssdev/appflow/commit/01f4cb6d90809dcfd37dc6958a30ac425f737c42 based on Docker, on OSX `sudo ifconfig lo0 alias 10.200.10.1/24 ; source ~/.appflow/config ; docker stop jenkins ; docker-compose up` then Jenkins will be on http://localhost:8080.
