### ISSUE TITLE
Enable mod_pagespeed

### ISSUE THREAD

**Issue by swissspidy** [ttssdev/appflow#52]
In `playbooks/roles/web/tasks/main.yml`, `mod_pagespeed` is currently [commented out](https://github.com/ttssdev/appflow/blob/31c14c6caa327fc6cc0cf6ac5f9c87ba000e6c8c/playbooks/roles/web/tasks/main.yml#L31).

Leveraging some filters of this Apache module would be very beneficial for overall performance of the websites running on Appflow. `mod_pagespeed` has filters to minimize request overhead, minimize payload size, and even filters to improve rendering time in the browser.

**Comment by grappler** [comment]
Are you sure `mod_pagespeed` works with memcached?

**Comment by swissspidy** [comment]
@grappler Why not?

Memcached is an object cache that will be used by WordPress to cache stuff. WordPress reads from the object cache and the database and returns some HTML. `mod_pagespeed` then optimizes all the things (e.g. minifies HTML) and sends it to the browser. Along the way, Varnish caches the data.

I'd rather have said using `mod_pagespeed` and Varnish together is troublesome, but from what I can see it should work. Perhaps `ModPagespeedModifyCachingHeaders` is needed.

If the setup is incompatible with Varnish, we should look into further tweaking Varnish, Apache and HAProxy to improve performance.

**Comment by ivomarino** [comment]
@swissspidy can be enabled, we just need to be sure to install latest version. The thing with `mod_pagespeed` is that it must be really carefully configured as you might know. There are many options and tunings.
