### ISSUE TITLE
Documentation: Add guides to wiki

### ISSUE THREAD

**Issue by neverything** [ttssdev/appflow#6]
I know this is just the beginning of the appflow setup, but it would be tremendously helpful to have some sort of documentation. The following parts would be great to have a documentation on:
- [x] Troubleshooting guide (common mistakes, error codes and how to fix)
- [x] Add new client project (in my case specifically for WordPress setups)
- [x] Document the common `make` commands of appflow
- [x] Common stuff like add PHP module and provision it on all nodes

I probably can help with the documentation or at least testing it out. Let me know if you'd need any help here.

**Comment by ivomarino** [comment]
blank https://github.com/ttssdev/appflow/wiki has been created for now, feel free to edit also, we can finetune then. Or put in your questions so we know what, from an user perspective, is needed.

**Comment by ivomarino** [comment]
We also need to split up the wiki in documentation for AppFlow users and AppFlow developers.

**Comment by ivomarino** [comment]
@neverything close this as covered by http://appflow.readthedocs.io/en/latest/.
