### ISSUE TITLE
Ansible Version

### ISSUE THREAD

**Issue by grappler** [ttssdev/appflow#75]
In https://github.com/ttssdev/appflow/issues/13 the required ansible version is `2.0.x`.

Recently in https://github.com/ttssdev/appflow/commit/946d49fd99dd950ce0d50252fedcac7ae33404fd `check_mode` is being used which is only avaible in ansible `2.2.x`.

Which versions of ansible are supported?

**Comment by ivomarino** [comment]
Latest ansible version is supported fine, you can find it in `brew` on macOS.

**Comment by ivomarino** [comment]
@grappler solved?

**Comment by grappler** [comment]
Yes, `2.3.x` seems to work. It would be to inform us if it changes. 😄
