### ISSUE TITLE
Provision should update hosts file automatically

### ISSUE THREAD

**Issue by ocean90** [ttssdev/appflow#8]
It would be handy if I could specify the URLs of a site somewhere so they get automatically added to my hosts file. This requires the [Vagrant::Hostsupdater](https://github.com/cogitatio/vagrant-hostsupdater) or [Vagrant Host Manager](https://github.com/devopsgroup-io/vagrant-hostmanager) plugin. (The latter one also updates the hosts file on the vm.)

[Varying Vagrant Vagrants](https://github.com/Varying-Vagrant-Vagrants/VVV/blob/838b694cfc9d25cf71fdfd2353244e8b545ac178/Vagrantfile#L79-L106) uses a file named [`vvv-hosts`](https://github.com/Varying-Vagrant-Vagrants/VVV/blob/838b694cfc9d25cf71fdfd2353244e8b545ac178/www/vvv-hosts) for this.

**Comment by ivomarino** [comment]
The urls of the vhosts are already available in the tenant's configs (encrypted files), we need to find a way for extracting them and push the list over to vagrant when brining up the VM, need to brainstrom over it.

**Comment by ivomarino** [comment]
solution is `appflow local`.

**Comment by ivomarino** [comment]
@89luca89 is working on this.

**Comment by 89luca89** [comment]
Added in new python porting.

appflow.py vhosts "tenant-name"
