### ISSUE TITLE
add snmp configuration

### ISSUE THREAD

**Issue by stefan-kalb** [ttssdev/appflow#81]
Extend appflow to contain snmp (v2) configuration.

**Comment by ivomarino** [comment]
@stefan-kalb: woodwing specific?

**Comment by stefan-kalb** [comment]
Nein, generell. Aber ich dachte bevor ich’s manuell auf allen Servern einstelle, kann ich’s auch grad über appflow einstellen und dann bekommen das auch unsere anderen Server, wenn wir wollen.

**Comment by ivomarino** [comment]
@stefan-kalb actually there's no `SNMP` support, feel free to implement it, should belong to `common`. For config options you should use something like:

```
#
# SNMP
#
conf_snmp_enable: true
conf_snmp_<setting_1>: whatever
conf_snmp_<setting_2>: whatever2
```

**Comment by stefan-kalb** [comment]
Added missing quotation marks to snmpd.conf.j2, fixed typo in variable name

**Comment by ivomarino** [comment]
@stefan-kalb can be closed?

**Comment by stefan-kalb** [comment]
It can be closed
