### ISSUE TITLE
woodwing: config.php / configserver.php removed at rollout

### ISSUE THREAD

**Issue by stefan-kalb** [ttssdev/appflow#93]
Problem:
When I rollout a new woodwing project config.php and configserver.php is removed from all projects (also with unchanged config options), which results in a downtime whilst the rollout process. With over 100 woodwing projects this results in a downtime of several minutes. Therefore changes / new customers can only applied in a maintenance window.

Expectation:
Just changed config-Files are removed / rewritten whilst a rollout.

**Comment by ivomarino** [comment]
@stefan-kalb, can be closed?

**Comment by stefan-kalb** [comment]
Yes. Was resolved by corrected rsync command

**Comment by ivomarino** [comment]
@stefan-kalb ok, thanks for info. I'll close it.
