### ISSUE TITLE
WordPress Config: Use https by default and/or add setting for https

### ISSUE THREAD

**Issue by ocean90** [ttssdev/appflow#95]
https://github.com/ttssdev/appflow/blob/8656fba970e380e3fc40ca51fb8baf0798508676/playbooks/roles/web/templates/wp_bedrock/env.j2#L17-L20

I think it's okay to just switch that to https by default. Thoughts?

**Comment by ivomarino** [comment]
needs to be tested I think, what exactly would this mean to WP sites?

**Comment by ocean90** [comment]
Well, the site and home URL would be HTTPS.

* https://codex.wordpress.org/Editing_wp-config.php#WP_SITEURL
* https://codex.wordpress.org/Editing_wp-config.php#WP_HOME

**Comment by ivomarino** [comment]
Could be an issue for internal Access via localhost like wp-cron or similar, remember?

**Comment by ivomarino** [comment]
We should test this on dev first, IMHO.

**Comment by neverything** [comment]
Is this resolved? What was the solution?

**Comment by ivomarino** [comment]
@neverything no idea actually, the only thing I know is that in case of SSL front-end offloading all the backend communication can be done via HTTP-only.

**Comment by ocean90** [comment]
You can use `Dotenv::overload()` to overwrite existing environment vars.

**Comment by ivomarino** [comment]
Issue can be closed in that case?

**Comment by neverything** [comment]
Yes, thanks @ocean90 and @ivomarino
